//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmoneyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.CreateInvoiceRequest))]
    public partial class Request : object
    {
        
        private string DistributorField;
        
        private string HashField;
        
        private EmoneyService.Parameter[] ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distributor
        {
            get
            {
                return this.DistributorField;
            }
            set
            {
                this.DistributorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Parameter[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateInvoiceRequest", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class CreateInvoiceRequest : EmoneyService.Request
    {
        
        private decimal AmountField;
        
        private string DescriptionField;
        
        private System.Nullable<int> ExpirationTimeHoursField;
        
        private EmoneyService.InvoiceProduct[] ProductsField;
        
        private System.Nullable<System.Guid> UnIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExpirationTimeHours
        {
            get
            {
                return this.ExpirationTimeHoursField;
            }
            set
            {
                this.ExpirationTimeHoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.InvoiceProduct[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UnId
        {
            get
            {
                return this.UnIdField;
            }
            set
            {
                this.UnIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameter", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class Parameter : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceProduct", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class InvoiceProduct : object
    {
        
        private decimal AmountField;
        
        private string CodeField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private decimal QuantityField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfRates))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfProvider))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfServiceProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfParameterReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfAccountBalance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfStatementEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfTransactionParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfTransactionFull))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfCreateInvoiceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfGetInvoiceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmoneyService.ResponseOfArrayOfProviderGroup))]
    public partial class Response : object
    {
        
        private int CodeField;
        
        private string ExtraInfoField;
        
        private string IDField;
        
        private string MessageField;
        
        private EmoneyService.SharedSystemCodes SystemCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.SharedSystemCodes SystemCode
        {
            get
            {
                return this.SystemCodeField;
            }
            set
            {
                this.SystemCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfRates", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfRates : EmoneyService.Response
    {
        
        private EmoneyService.Rates[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Rates[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfProvider", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfProvider : EmoneyService.Response
    {
        
        private EmoneyService.Provider[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Provider[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfServiceProperty", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfServiceProperty : EmoneyService.Response
    {
        
        private EmoneyService.ServiceProperty ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ServiceProperty Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfParameterReference", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfParameterReference : EmoneyService.Response
    {
        
        private EmoneyService.ParameterReference[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ParameterReference[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfParameter", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfParameter : EmoneyService.Response
    {
        
        private EmoneyService.Parameter[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Parameter[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfstring", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfstring : EmoneyService.Response
    {
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfTransaction", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfTransaction : EmoneyService.Response
    {
        
        private EmoneyService.Transaction ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Transaction Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfAccountBalance", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfAccountBalance : EmoneyService.Response
    {
        
        private EmoneyService.AccountBalance[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.AccountBalance[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfStatementEntry", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfStatementEntry : EmoneyService.Response
    {
        
        private EmoneyService.StatementEntry[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.StatementEntry[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfTransactionParameter", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfTransactionParameter : EmoneyService.Response
    {
        
        private EmoneyService.TransactionParameter[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.TransactionParameter[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfTransactionFull", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfTransactionFull : EmoneyService.Response
    {
        
        private EmoneyService.TransactionFull ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.TransactionFull Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfCreateInvoiceResponse", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfCreateInvoiceResponse : EmoneyService.Response
    {
        
        private EmoneyService.CreateInvoiceResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.CreateInvoiceResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfGetInvoiceResponse", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfGetInvoiceResponse : EmoneyService.Response
    {
        
        private EmoneyService.GetInvoiceResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.GetInvoiceResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfProviderGroup", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public partial class ResponseOfArrayOfProviderGroup : EmoneyService.Response
    {
        
        private EmoneyService.ProviderGroup[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ProviderGroup[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SharedSystemCodes", Namespace="http://schemas.datacontract.org/2004/07/LB.Shared")]
    public enum SharedSystemCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenericError = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retry = -2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProviderGroup", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class ProviderGroup : object
    {
        
        private int IDField;
        
        private string ImageURLField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this.ImageURLField;
            }
            set
            {
                this.ImageURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rates", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class Rates : object
    {
        
        private decimal BuyRateField;
        
        private decimal BuyScaleField;
        
        private string Currency1Field;
        
        private string Currency1AbbrField;
        
        private string Currency2Field;
        
        private string Currency2AbbrField;
        
        private decimal SellRateField;
        
        private decimal SellScaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BuyRate
        {
            get
            {
                return this.BuyRateField;
            }
            set
            {
                this.BuyRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BuyScale
        {
            get
            {
                return this.BuyScaleField;
            }
            set
            {
                this.BuyScaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency1
        {
            get
            {
                return this.Currency1Field;
            }
            set
            {
                this.Currency1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency1Abbr
        {
            get
            {
                return this.Currency1AbbrField;
            }
            set
            {
                this.Currency1AbbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency2
        {
            get
            {
                return this.Currency2Field;
            }
            set
            {
                this.Currency2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency2Abbr
        {
            get
            {
                return this.Currency2AbbrField;
            }
            set
            {
                this.Currency2AbbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SellRate
        {
            get
            {
                return this.SellRateField;
            }
            set
            {
                this.SellRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SellScale
        {
            get
            {
                return this.SellScaleField;
            }
            set
            {
                this.SellScaleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class Provider : object
    {
        
        private int IDField;
        
        private string ImageURLField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this.ImageURLField;
            }
            set
            {
                this.ImageURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceProperty", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class ServiceProperty : object
    {
        
        private EmoneyService.ServiceParameter[] ParametersField;
        
        private EmoneyService.Property PropertyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ServiceParameter[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Property Property
        {
            get
            {
                return this.PropertyField;
            }
            set
            {
                this.PropertyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class Property : object
    {
        
        private decimal CommissionRateField;
        
        private string CurrencyField;
        
        private string DescriptionField;
        
        private string DetailsField;
        
        private decimal ExchangeRateField;
        
        private string GroupDescriptionField;
        
        private int GroupIDField;
        
        private string ImgURLField;
        
        private decimal MaxAmountField;
        
        private decimal MinAmountField;
        
        private decimal MinCommissionField;
        
        private decimal RoundingField;
        
        private int ServiceIDField;
        
        private EmoneyService.ServiceType ServiceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CommissionRate
        {
            get
            {
                return this.CommissionRateField;
            }
            set
            {
                this.CommissionRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate
        {
            get
            {
                return this.ExchangeRateField;
            }
            set
            {
                this.ExchangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupDescription
        {
            get
            {
                return this.GroupDescriptionField;
            }
            set
            {
                this.GroupDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgURL
        {
            get
            {
                return this.ImgURLField;
            }
            set
            {
                this.ImgURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxAmount
        {
            get
            {
                return this.MaxAmountField;
            }
            set
            {
                this.MaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinAmount
        {
            get
            {
                return this.MinAmountField;
            }
            set
            {
                this.MinAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinCommission
        {
            get
            {
                return this.MinCommissionField;
            }
            set
            {
                this.MinCommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rounding
        {
            get
            {
                return this.RoundingField;
            }
            set
            {
                this.RoundingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceID
        {
            get
            {
                return this.ServiceIDField;
            }
            set
            {
                this.ServiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ServiceType ServiceType
        {
            get
            {
                return this.ServiceTypeField;
            }
            set
            {
                this.ServiceTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceParameter", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class ServiceParameter : object
    {
        
        private string DescriptionField;
        
        private int IDField;
        
        private string MaskField;
        
        private string NameField;
        
        private EmoneyService.ParameterReference[] ParametersField;
        
        private int ServiceIDField;
        
        private string TooltipField;
        
        private EmoneyService.ServiceParameterType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ParameterReference[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceID
        {
            get
            {
                return this.ServiceIDField;
            }
            set
            {
                this.ServiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tooltip
        {
            get
            {
                return this.TooltipField;
            }
            set
            {
                this.TooltipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ServiceParameterType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterReference", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class ParameterReference : object
    {
        
        private int IDField;
        
        private string NameField;
        
        private long ParameterIDField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParameterID
        {
            get
            {
                return this.ParameterIDField;
            }
            set
            {
                this.ParameterIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceParameterType", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public enum ServiceParameterType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        List = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateField = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OptionalTextField = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HiddenEmptyField = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HiddenFieldWithDefaultValue = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoStepMultiselect = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoStepSingleselect = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MergeWithTransactioncode = 17,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public enum ServiceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multicheck = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class Transaction : object
    {
        
        private decimal AmountField;
        
        private long CodeField;
        
        private string CurrencyField;
        
        private string DescriptionField;
        
        private long IDField;
        
        private string IPField;
        
        private EmoneyService.ReceiverIdentities ReceiverIdentitiesField;
        
        private EmoneyService.TransactionStatus StatusField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.ReceiverIdentities ReceiverIdentities
        {
            get
            {
                return this.ReceiverIdentitiesField;
            }
            set
            {
                this.ReceiverIdentitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.TransactionStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverIdentities", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class ReceiverIdentities : object
    {
        
        private string _nb_first_nameField;
        
        private string _nb_last_nameField;
        
        private string _nb_personal_numberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _nb_first_name
        {
            get
            {
                return this._nb_first_nameField;
            }
            set
            {
                this._nb_first_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _nb_last_name
        {
            get
            {
                return this._nb_last_nameField;
            }
            set
            {
                this._nb_last_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _nb_personal_number
        {
            get
            {
                return this._nb_personal_numberField;
            }
            set
            {
                this._nb_personal_numberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public enum TransactionStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registered = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = -100,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalance", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class AccountBalance : object
    {
        
        private long AccountField;
        
        private decimal BalanceField;
        
        private string CurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementEntry", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class StatementEntry : object
    {
        
        private decimal AmountField;
        
        private long CodeField;
        
        private long CreditField;
        
        private string CurrencyField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private long DebitField;
        
        private string DescriptionField;
        
        private long IDField;
        
        private EmoneyService.TransactionStatus StatusField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Debit
        {
            get
            {
                return this.DebitField;
            }
            set
            {
                this.DebitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.TransactionStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionParameter", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class TransactionParameter : object
    {
        
        private System.Nullable<System.DateTime> ChangedField;
        
        private long IDField;
        
        private string ParameterCodeField;
        
        private long ParameterTypeField;
        
        private string ParameterValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Changed
        {
            get
            {
                return this.ChangedField;
            }
            set
            {
                this.ChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterCode
        {
            get
            {
                return this.ParameterCodeField;
            }
            set
            {
                this.ParameterCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParameterType
        {
            get
            {
                return this.ParameterTypeField;
            }
            set
            {
                this.ParameterTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterValue
        {
            get
            {
                return this.ParameterValueField;
            }
            set
            {
                this.ParameterValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionFull", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class TransactionFull : object
    {
        
        private decimal AmountField;
        
        private long CodeField;
        
        private decimal CommissionField;
        
        private string CreditField;
        
        private string CurrencyField;
        
        private string DebitField;
        
        private string DescriptionField;
        
        private long IDField;
        
        private string IPField;
        
        private EmoneyService.Parameter[] PrametersField;
        
        private EmoneyService.TransactionStatus StatusField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Commission
        {
            get
            {
                return this.CommissionField;
            }
            set
            {
                this.CommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Debit
        {
            get
            {
                return this.DebitField;
            }
            set
            {
                this.DebitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.Parameter[] Prameters
        {
            get
            {
                return this.PrametersField;
            }
            set
            {
                this.PrametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.TransactionStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateInvoiceResponse", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class CreateInvoiceResponse : object
    {
        
        private decimal AmountField;
        
        private string CodeField;
        
        private string ExpirationDateField;
        
        private uint InvoiceIdField;
        
        private System.Nullable<System.Guid> UnIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint InvoiceId
        {
            get
            {
                return this.InvoiceIdField;
            }
            set
            {
                this.InvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UnId
        {
            get
            {
                return this.UnIdField;
            }
            set
            {
                this.UnIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInvoiceResponse", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class GetInvoiceResponse : object
    {
        
        private decimal AmountField;
        
        private string CodeField;
        
        private string CreateTimeField;
        
        private string DescriptionField;
        
        private string ExpirationTimeField;
        
        private uint InvoiceIdField;
        
        private bool IsPayedField;
        
        private System.Nullable<decimal> PayedAmountField;
        
        private EmoneyService.InvoicePayment[] PaymentsField;
        
        private EmoneyService.InvoiceProduct[] ProductsField;
        
        private int StatusField;
        
        private System.Nullable<System.Guid> UnIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpirationTime
        {
            get
            {
                return this.ExpirationTimeField;
            }
            set
            {
                this.ExpirationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint InvoiceId
        {
            get
            {
                return this.InvoiceIdField;
            }
            set
            {
                this.InvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPayed
        {
            get
            {
                return this.IsPayedField;
            }
            set
            {
                this.IsPayedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PayedAmount
        {
            get
            {
                return this.PayedAmountField;
            }
            set
            {
                this.PayedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.InvoicePayment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmoneyService.InvoiceProduct[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UnId
        {
            get
            {
                return this.UnIdField;
            }
            set
            {
                this.UnIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoicePayment", Namespace="http://schemas.datacontract.org/2004/07/EmoneyDistributorService.Model")]
    public partial class InvoicePayment : object
    {
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private int StatusField;
        
        private uint TransactionCodeField;
        
        private uint TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmoneyService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServiceGroups", ReplyAction="http://tempuri.org/IService/GetServiceGroupsResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfProviderGroup> GetServiceGroupsAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRates", ReplyAction="http://tempuri.org/IService/GetRatesResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfRates> GetRatesAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServices", ReplyAction="http://tempuri.org/IService/GetServicesResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfProvider> GetServicesAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServiceProperties", ReplyAction="http://tempuri.org/IService/GetServicePropertiesResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfServiceProperty> GetServicePropertiesAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServiceParameterReferences", ReplyAction="http://tempuri.org/IService/GetServiceParameterReferencesResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameterReference> GetServiceParameterReferencesAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInfo", ReplyAction="http://tempuri.org/IService/GetInfoResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameter> GetInfoAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckCode", ReplyAction="http://tempuri.org/IService/CheckCodeResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> CheckCodeAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendCode", ReplyAction="http://tempuri.org/IService/SendCodeResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> SendCodeAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Pay", ReplyAction="http://tempuri.org/IService/PayResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> PayAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConfirmPayment", ReplyAction="http://tempuri.org/IService/ConfirmPaymentResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> ConfirmPaymentAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTransactionInfo", ReplyAction="http://tempuri.org/IService/GetTransactionInfoResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> GetTransactionInfoAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBalance", ReplyAction="http://tempuri.org/IService/GetBalanceResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfAccountBalance> GetBalanceAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStatement", ReplyAction="http://tempuri.org/IService/GetStatementResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfStatementEntry> GetStatementAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTransactionDetails", ReplyAction="http://tempuri.org/IService/GetTransactionDetailsResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfTransactionParameter> GetTransactionDetailsAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelTransaction", ReplyAction="http://tempuri.org/IService/CancelTransactionResponse")]
        System.Threading.Tasks.Task<EmoneyService.Response> CancelTransactionAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFullTransactionInfo", ReplyAction="http://tempuri.org/IService/GetFullTransactionInfoResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfTransactionFull> GetFullTransactionInfoAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterParcel", ReplyAction="http://tempuri.org/IService/RegisterParcelResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> RegisterParcelAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GeteMoneyInfoByPrivateID", ReplyAction="http://tempuri.org/IService/GeteMoneyInfoByPrivateIDResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameter> GeteMoneyInfoByPrivateIDAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrepareWithdrawFromeMoney", ReplyAction="http://tempuri.org/IService/PrepareWithdrawFromeMoneyResponse")]
        System.Threading.Tasks.Task<EmoneyService.Response> PrepareWithdrawFromeMoneyAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WithdrawFromeMoney", ReplyAction="http://tempuri.org/IService/WithdrawFromeMoneyResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> WithdrawFromeMoneyAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateInvoice", ReplyAction="http://tempuri.org/IService/CreateInvoiceResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfCreateInvoiceResponse> CreateInvoiceAsync(EmoneyService.CreateInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInvoice", ReplyAction="http://tempuri.org/IService/GetInvoiceResponse")]
        System.Threading.Tasks.Task<EmoneyService.ResponseOfGetInvoiceResponse> GetInvoiceAsync(EmoneyService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelInvoice", ReplyAction="http://tempuri.org/IService/CancelInvoiceResponse")]
        System.Threading.Tasks.Task<EmoneyService.Response> CancelInvoiceAsync(EmoneyService.Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceChannel : EmoneyService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EmoneyService.IService>, EmoneyService.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfProviderGroup> GetServiceGroupsAsync(EmoneyService.Request request)
        {
            return base.Channel.GetServiceGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfRates> GetRatesAsync(EmoneyService.Request request)
        {
            return base.Channel.GetRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfProvider> GetServicesAsync(EmoneyService.Request request)
        {
            return base.Channel.GetServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfServiceProperty> GetServicePropertiesAsync(EmoneyService.Request request)
        {
            return base.Channel.GetServicePropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameterReference> GetServiceParameterReferencesAsync(EmoneyService.Request request)
        {
            return base.Channel.GetServiceParameterReferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameter> GetInfoAsync(EmoneyService.Request request)
        {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> CheckCodeAsync(EmoneyService.Request request)
        {
            return base.Channel.CheckCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> SendCodeAsync(EmoneyService.Request request)
        {
            return base.Channel.SendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> PayAsync(EmoneyService.Request request)
        {
            return base.Channel.PayAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> ConfirmPaymentAsync(EmoneyService.Request request)
        {
            return base.Channel.ConfirmPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> GetTransactionInfoAsync(EmoneyService.Request request)
        {
            return base.Channel.GetTransactionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfAccountBalance> GetBalanceAsync(EmoneyService.Request request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfStatementEntry> GetStatementAsync(EmoneyService.Request request)
        {
            return base.Channel.GetStatementAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfTransactionParameter> GetTransactionDetailsAsync(EmoneyService.Request request)
        {
            return base.Channel.GetTransactionDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.Response> CancelTransactionAsync(EmoneyService.Request request)
        {
            return base.Channel.CancelTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfTransactionFull> GetFullTransactionInfoAsync(EmoneyService.Request request)
        {
            return base.Channel.GetFullTransactionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfstring> RegisterParcelAsync(EmoneyService.Request request)
        {
            return base.Channel.RegisterParcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfArrayOfParameter> GeteMoneyInfoByPrivateIDAsync(EmoneyService.Request request)
        {
            return base.Channel.GeteMoneyInfoByPrivateIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.Response> PrepareWithdrawFromeMoneyAsync(EmoneyService.Request request)
        {
            return base.Channel.PrepareWithdrawFromeMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfTransaction> WithdrawFromeMoneyAsync(EmoneyService.Request request)
        {
            return base.Channel.WithdrawFromeMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfCreateInvoiceResponse> CreateInvoiceAsync(EmoneyService.CreateInvoiceRequest request)
        {
            return base.Channel.CreateInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.ResponseOfGetInvoiceResponse> GetInvoiceAsync(EmoneyService.Request request)
        {
            return base.Channel.GetInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmoneyService.Response> CancelInvoiceAsync(EmoneyService.Request request)
        {
            return base.Channel.CancelInvoiceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("https://api.emoney.ge/distributors/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
